export interface Country {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
}

function flag(code: string): string {
  return [...code.toUpperCase()].map(c => String.fromCodePoint(c.charCodeAt(0) + 0x1F1A5)).join('');
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", dialCode: "+93", flag: flag("AF") },
  { name: "Afrique du Sud", code: "ZA", dialCode: "+27", flag: flag("ZA") },
  { name: "Albanie", code: "AL", dialCode: "+355", flag: flag("AL") },
  { name: "Algérie", code: "DZ", dialCode: "+213", flag: flag("DZ") },
  { name: "Allemagne", code: "DE", dialCode: "+49", flag: flag("DE") },
  { name: "Andorre", code: "AD", dialCode: "+376", flag: flag("AD") },
  { name: "Angola", code: "AO", dialCode: "+244", flag: flag("AO") },
  { name: "Antigua-et-Barbuda", code: "AG", dialCode: "+1268", flag: flag("AG") },
  { name: "Arabie saoudite", code: "SA", dialCode: "+966", flag: flag("SA") },
  { name: "Argentine", code: "AR", dialCode: "+54", flag: flag("AR") },
  { name: "Arménie", code: "AM", dialCode: "+374", flag: flag("AM") },
  { name: "Australie", code: "AU", dialCode: "+61", flag: flag("AU") },
  { name: "Autriche", code: "AT", dialCode: "+43", flag: flag("AT") },
  { name: "Azerbaïdjan", code: "AZ", dialCode: "+994", flag: flag("AZ") },
  { name: "Bahamas", code: "BS", dialCode: "+1242", flag: flag("BS") },
  { name: "Bahreïn", code: "BH", dialCode: "+973", flag: flag("BH") },
  { name: "Bangladesh", code: "BD", dialCode: "+880", flag: flag("BD") },
  { name: "Barbade", code: "BB", dialCode: "+1246", flag: flag("BB") },
  { name: "Bélarus", code: "BY", dialCode: "+375", flag: flag("BY") },
  { name: "Belgique", code: "BE", dialCode: "+32", flag: flag("BE") },
  { name: "Belize", code: "BZ", dialCode: "+501", flag: flag("BZ") },
  { name: "Bénin", code: "BJ", dialCode: "+229", flag: flag("BJ") },
  { name: "Bhoutan", code: "BT", dialCode: "+975", flag: flag("BT") },
  { name: "Bolivie", code: "BO", dialCode: "+591", flag: flag("BO") },
  { name: "Bosnie-Herzégovine", code: "BA", dialCode: "+387", flag: flag("BA") },
  { name: "Botswana", code: "BW", dialCode: "+267", flag: flag("BW") },
  { name: "Brésil", code: "BR", dialCode: "+55", flag: flag("BR") },
  { name: "Brunei", code: "BN", dialCode: "+673", flag: flag("BN") },
  { name: "Bulgarie", code: "BG", dialCode: "+359", flag: flag("BG") },
  { name: "Burkina Faso", code: "BF", dialCode: "+226", flag: flag("BF") },
  { name: "Burundi", code: "BI", dialCode: "+257", flag: flag("BI") },
  { name: "Cabo Verde", code: "CV", dialCode: "+238", flag: flag("CV") },
  { name: "Cambodge", code: "KH", dialCode: "+855", flag: flag("KH") },
  { name: "Cameroun", code: "CM", dialCode: "+237", flag: flag("CM") },
  { name: "Canada", code: "CA", dialCode: "+1", flag: flag("CA") },
  { name: "Centrafrique", code: "CF", dialCode: "+236", flag: flag("CF") },
  { name: "Chili", code: "CL", dialCode: "+56", flag: flag("CL") },
  { name: "Chine", code: "CN", dialCode: "+86", flag: flag("CN") },
  { name: "Chypre", code: "CY", dialCode: "+357", flag: flag("CY") },
  { name: "Colombie", code: "CO", dialCode: "+57", flag: flag("CO") },
  { name: "Comores", code: "KM", dialCode: "+269", flag: flag("KM") },
  { name: "Congo", code: "CG", dialCode: "+242", flag: flag("CG") },
  { name: "Congo (RDC)", code: "CD", dialCode: "+243", flag: flag("CD") },
  { name: "Corée du Nord", code: "KP", dialCode: "+850", flag: flag("KP") },
  { name: "Corée du Sud", code: "KR", dialCode: "+82", flag: flag("KR") },
  { name: "Costa Rica", code: "CR", dialCode: "+506", flag: flag("CR") },
  { name: "Côte d'Ivoire", code: "CI", dialCode: "+225", flag: flag("CI") },
  { name: "Croatie", code: "HR", dialCode: "+385", flag: flag("HR") },
  { name: "Cuba", code: "CU", dialCode: "+53", flag: flag("CU") },
  { name: "Danemark", code: "DK", dialCode: "+45", flag: flag("DK") },
  { name: "Djibouti", code: "DJ", dialCode: "+253", flag: flag("DJ") },
  { name: "Dominique", code: "DM", dialCode: "+1767", flag: flag("DM") },
  { name: "Égypte", code: "EG", dialCode: "+20", flag: flag("EG") },
  { name: "El Salvador", code: "SV", dialCode: "+503", flag: flag("SV") },
  { name: "Émirats arabes unis", code: "AE", dialCode: "+971", flag: flag("AE") },
  { name: "Équateur", code: "EC", dialCode: "+593", flag: flag("EC") },
  { name: "Érythrée", code: "ER", dialCode: "+291", flag: flag("ER") },
  { name: "Espagne", code: "ES", dialCode: "+34", flag: flag("ES") },
  { name: "Eswatini", code: "SZ", dialCode: "+268", flag: flag("SZ") },
  { name: "Estonie", code: "EE", dialCode: "+372", flag: flag("EE") },
  { name: "États-Unis", code: "US", dialCode: "+1", flag: flag("US") },
  { name: "Éthiopie", code: "ET", dialCode: "+251", flag: flag("ET") },
  { name: "Fidji", code: "FJ", dialCode: "+679", flag: flag("FJ") },
  { name: "Finlande", code: "FI", dialCode: "+358", flag: flag("FI") },
  { name: "France", code: "FR", dialCode: "+33", flag: flag("FR") },
  { name: "Gabon", code: "GA", dialCode: "+241", flag: flag("GA") },
  { name: "Gambie", code: "GM", dialCode: "+220", flag: flag("GM") },
  { name: "Géorgie", code: "GE", dialCode: "+995", flag: flag("GE") },
  { name: "Ghana", code: "GH", dialCode: "+233", flag: flag("GH") },
  { name: "Grèce", code: "GR", dialCode: "+30", flag: flag("GR") },
  { name: "Grenade", code: "GD", dialCode: "+1473", flag: flag("GD") },
  { name: "Guatemala", code: "GT", dialCode: "+502", flag: flag("GT") },
  { name: "Guinée", code: "GN", dialCode: "+224", flag: flag("GN") },
  { name: "Guinée-Bissau", code: "GW", dialCode: "+245", flag: flag("GW") },
  { name: "Guinée équatoriale", code: "GQ", dialCode: "+240", flag: flag("GQ") },
  { name: "Guyana", code: "GY", dialCode: "+592", flag: flag("GY") },
  { name: "Haïti", code: "HT", dialCode: "+509", flag: flag("HT") },
  { name: "Honduras", code: "HN", dialCode: "+504", flag: flag("HN") },
  { name: "Hongrie", code: "HU", dialCode: "+36", flag: flag("HU") },
  { name: "Îles Marshall", code: "MH", dialCode: "+692", flag: flag("MH") },
  { name: "Îles Salomon", code: "SB", dialCode: "+677", flag: flag("SB") },
  { name: "Inde", code: "IN", dialCode: "+91", flag: flag("IN") },
  { name: "Indonésie", code: "ID", dialCode: "+62", flag: flag("ID") },
  { name: "Irak", code: "IQ", dialCode: "+964", flag: flag("IQ") },
  { name: "Iran", code: "IR", dialCode: "+98", flag: flag("IR") },
  { name: "Irlande", code: "IE", dialCode: "+353", flag: flag("IE") },
  { name: "Islande", code: "IS", dialCode: "+354", flag: flag("IS") },
  { name: "Israël", code: "IL", dialCode: "+972", flag: flag("IL") },
  { name: "Italie", code: "IT", dialCode: "+39", flag: flag("IT") },
  { name: "Jamaïque", code: "JM", dialCode: "+1876", flag: flag("JM") },
  { name: "Japon", code: "JP", dialCode: "+81", flag: flag("JP") },
  { name: "Jordanie", code: "JO", dialCode: "+962", flag: flag("JO") },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: flag("KZ") },
  { name: "Kenya", code: "KE", dialCode: "+254", flag: flag("KE") },
  { name: "Kirghizistan", code: "KG", dialCode: "+996", flag: flag("KG") },
  { name: "Kiribati", code: "KI", dialCode: "+686", flag: flag("KI") },
  { name: "Kosovo", code: "XK", dialCode: "+383", flag: flag("XK") },
  { name: "Koweït", code: "KW", dialCode: "+965", flag: flag("KW") },
  { name: "Laos", code: "LA", dialCode: "+856", flag: flag("LA") },
  { name: "Lesotho", code: "LS", dialCode: "+266", flag: flag("LS") },
  { name: "Lettonie", code: "LV", dialCode: "+371", flag: flag("LV") },
  { name: "Liban", code: "LB", dialCode: "+961", flag: flag("LB") },
  { name: "Liberia", code: "LR", dialCode: "+231", flag: flag("LR") },
  { name: "Libye", code: "LY", dialCode: "+218", flag: flag("LY") },
  { name: "Liechtenstein", code: "LI", dialCode: "+423", flag: flag("LI") },
  { name: "Lituanie", code: "LT", dialCode: "+370", flag: flag("LT") },
  { name: "Luxembourg", code: "LU", dialCode: "+352", flag: flag("LU") },
  { name: "Madagascar", code: "MG", dialCode: "+261", flag: flag("MG") },
  { name: "Malaisie", code: "MY", dialCode: "+60", flag: flag("MY") },
  { name: "Malawi", code: "MW", dialCode: "+265", flag: flag("MW") },
  { name: "Maldives", code: "MV", dialCode: "+960", flag: flag("MV") },
  { name: "Mali", code: "ML", dialCode: "+223", flag: flag("ML") },
  { name: "Malte", code: "MT", dialCode: "+356", flag: flag("MT") },
  { name: "Maroc", code: "MA", dialCode: "+212", flag: flag("MA") },
  { name: "Maurice", code: "MU", dialCode: "+230", flag: flag("MU") },
  { name: "Mauritanie", code: "MR", dialCode: "+222", flag: flag("MR") },
  { name: "Mexique", code: "MX", dialCode: "+52", flag: flag("MX") },
  { name: "Micronésie", code: "FM", dialCode: "+691", flag: flag("FM") },
  { name: "Moldavie", code: "MD", dialCode: "+373", flag: flag("MD") },
  { name: "Monaco", code: "MC", dialCode: "+377", flag: flag("MC") },
  { name: "Mongolie", code: "MN", dialCode: "+976", flag: flag("MN") },
  { name: "Monténégro", code: "ME", dialCode: "+382", flag: flag("ME") },
  { name: "Mozambique", code: "MZ", dialCode: "+258", flag: flag("MZ") },
  { name: "Myanmar", code: "MM", dialCode: "+95", flag: flag("MM") },
  { name: "Namibie", code: "NA", dialCode: "+264", flag: flag("NA") },
  { name: "Nauru", code: "NR", dialCode: "+674", flag: flag("NR") },
  { name: "Népal", code: "NP", dialCode: "+977", flag: flag("NP") },
  { name: "Nicaragua", code: "NI", dialCode: "+505", flag: flag("NI") },
  { name: "Niger", code: "NE", dialCode: "+227", flag: flag("NE") },
  { name: "Nigeria", code: "NG", dialCode: "+234", flag: flag("NG") },
  { name: "Niue", code: "NU", dialCode: "+683", flag: flag("NU") },
  { name: "Norvège", code: "NO", dialCode: "+47", flag: flag("NO") },
  { name: "Nouvelle-Zélande", code: "NZ", dialCode: "+64", flag: flag("NZ") },
  { name: "Oman", code: "OM", dialCode: "+968", flag: flag("OM") },
  { name: "Ouganda", code: "UG", dialCode: "+256", flag: flag("UG") },
  { name: "Ouzbékistan", code: "UZ", dialCode: "+998", flag: flag("UZ") },
  { name: "Pakistan", code: "PK", dialCode: "+92", flag: flag("PK") },
  { name: "Palaos", code: "PW", dialCode: "+680", flag: flag("PW") },
  { name: "Palestine", code: "PS", dialCode: "+970", flag: flag("PS") },
  { name: "Panama", code: "PA", dialCode: "+507", flag: flag("PA") },
  { name: "Papouasie-Nouvelle-Guinée", code: "PG", dialCode: "+675", flag: flag("PG") },
  { name: "Paraguay", code: "PY", dialCode: "+595", flag: flag("PY") },
  { name: "Pays-Bas", code: "NL", dialCode: "+31", flag: flag("NL") },
  { name: "Pérou", code: "PE", dialCode: "+51", flag: flag("PE") },
  { name: "Philippines", code: "PH", dialCode: "+63", flag: flag("PH") },
  { name: "Pologne", code: "PL", dialCode: "+48", flag: flag("PL") },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: flag("PT") },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: flag("QA") },
  { name: "République dominicaine", code: "DO", dialCode: "+1809", flag: flag("DO") },
  { name: "République tchèque", code: "CZ", dialCode: "+420", flag: flag("CZ") },
  { name: "Roumanie", code: "RO", dialCode: "+40", flag: flag("RO") },
  { name: "Royaume-Uni", code: "GB", dialCode: "+44", flag: flag("GB") },
  { name: "Russie", code: "RU", dialCode: "+7", flag: flag("RU") },
  { name: "Rwanda", code: "RW", dialCode: "+250", flag: flag("RW") },
  { name: "Saint-Christophe-et-Niévès", code: "KN", dialCode: "+1869", flag: flag("KN") },
  { name: "Saint-Marin", code: "SM", dialCode: "+378", flag: flag("SM") },
  { name: "Saint-Vincent-et-les-Grenadines", code: "VC", dialCode: "+1784", flag: flag("VC") },
  { name: "Sainte-Lucie", code: "LC", dialCode: "+1758", flag: flag("LC") },
  { name: "Samoa", code: "WS", dialCode: "+685", flag: flag("WS") },
  { name: "Sao Tomé-et-Principe", code: "ST", dialCode: "+239", flag: flag("ST") },
  { name: "Sénégal", code: "SN", dialCode: "+221", flag: flag("SN") },
  { name: "Serbie", code: "RS", dialCode: "+381", flag: flag("RS") },
  { name: "Seychelles", code: "SC", dialCode: "+248", flag: flag("SC") },
  { name: "Sierra Leone", code: "SL", dialCode: "+232", flag: flag("SL") },
  { name: "Singapour", code: "SG", dialCode: "+65", flag: flag("SG") },
  { name: "Slovaquie", code: "SK", dialCode: "+421", flag: flag("SK") },
  { name: "Slovénie", code: "SI", dialCode: "+386", flag: flag("SI") },
  { name: "Somalie", code: "SO", dialCode: "+252", flag: flag("SO") },
  { name: "Soudan", code: "SD", dialCode: "+249", flag: flag("SD") },
  { name: "Soudan du Sud", code: "SS", dialCode: "+211", flag: flag("SS") },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", flag: flag("LK") },
  { name: "Suède", code: "SE", dialCode: "+46", flag: flag("SE") },
  { name: "Suisse", code: "CH", dialCode: "+41", flag: flag("CH") },
  { name: "Suriname", code: "SR", dialCode: "+597", flag: flag("SR") },
  { name: "Syrie", code: "SY", dialCode: "+963", flag: flag("SY") },
  { name: "Tadjikistan", code: "TJ", dialCode: "+992", flag: flag("TJ") },
  { name: "Tanzanie", code: "TZ", dialCode: "+255", flag: flag("TZ") },
  { name: "Tchad", code: "TD", dialCode: "+235", flag: flag("TD") },
  { name: "Thaïlande", code: "TH", dialCode: "+66", flag: flag("TH") },
  { name: "Timor-Leste", code: "TL", dialCode: "+670", flag: flag("TL") },
  { name: "Togo", code: "TG", dialCode: "+228", flag: flag("TG") },
  { name: "Tonga", code: "TO", dialCode: "+676", flag: flag("TO") },
  { name: "Trinité-et-Tobago", code: "TT", dialCode: "+1868", flag: flag("TT") },
  { name: "Tunisie", code: "TN", dialCode: "+216", flag: flag("TN") },
  { name: "Turkménistan", code: "TM", dialCode: "+993", flag: flag("TM") },
  { name: "Turquie", code: "TR", dialCode: "+90", flag: flag("TR") },
  { name: "Tuvalu", code: "TV", dialCode: "+688", flag: flag("TV") },
  { name: "Ukraine", code: "UA", dialCode: "+380", flag: flag("UA") },
  { name: "Uruguay", code: "UY", dialCode: "+598", flag: flag("UY") },
  { name: "Vanuatu", code: "VU", dialCode: "+678", flag: flag("VU") },
  { name: "Vatican", code: "VA", dialCode: "+39", flag: flag("VA") },
  { name: "Venezuela", code: "VE", dialCode: "+58", flag: flag("VE") },
  { name: "Vietnam", code: "VN", dialCode: "+84", flag: flag("VN") },
  { name: "Yémen", code: "YE", dialCode: "+967", flag: flag("YE") },
  { name: "Zambie", code: "ZM", dialCode: "+260", flag: flag("ZM") },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: flag("ZW") },
].sort((a, b) => a.name.localeCompare(b.name, 'fr'));

// Build a map of dialCode -> country for reverse lookup
// When multiple countries share +1, we prefer "États-Unis"
export const DIAL_CODE_MAP: Record<string, Country> = {};
[...COUNTRIES].reverse().forEach(c => {
  DIAL_CODE_MAP[c.dialCode] = c;
});
// Ensure +1 resolves to États-Unis (last write wins after reverse)
DIAL_CODE_MAP["+1"] = COUNTRIES.find(c => c.code === "US")!;
DIAL_CODE_MAP["+7"] = COUNTRIES.find(c => c.code === "RU")!;

export function findCountryByDialCode(input: string): Country | null {
  // Try longest match first (+1876 before +1)
  const digits = input.startsWith("+") ? input : "+" + input;
  for (const len of [5, 4, 3, 2]) {
    const prefix = digits.slice(0, len + 1); // +XXXX
    if (DIAL_CODE_MAP[prefix]) return DIAL_CODE_MAP[prefix];
  }
  return null;
}
